use_frameworks!

platform :ios, '9.0'

target 'HZCategoryKit_Example' do
  pod 'HZCategoryKit', :path => '../'

  target 'HZCategoryKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
